repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy src
    language: system
    types: [python]
