# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from eventstore_grpc.proto import serverfeatures_pb2 as serverfeatures__pb2
from eventstore_grpc.proto import shared_pb2 as shared__pb2


class ServerFeaturesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedMethods = channel.unary_unary(
            "/event_store.client.server_features.ServerFeatures/GetSupportedMethods",
            request_serializer=shared__pb2.Empty.SerializeToString,
            response_deserializer=serverfeatures__pb2.SupportedMethods.FromString,
        )


class ServerFeaturesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSupportedMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ServerFeaturesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSupportedMethods": grpc.unary_unary_rpc_method_handler(
            servicer.GetSupportedMethods,
            request_deserializer=shared__pb2.Empty.FromString,
            response_serializer=serverfeatures__pb2.SupportedMethods.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "event_store.client.server_features.ServerFeatures", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ServerFeatures(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSupportedMethods(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/event_store.client.server_features.ServerFeatures/GetSupportedMethods",
            shared__pb2.Empty.SerializeToString,
            serverfeatures__pb2.SupportedMethods.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
