# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared.proto',
  package='event_store.client.shared',
  syntax='proto3',
  serialized_options=b'\n$com.eventstore.dbclient.proto.shared',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cshared.proto\x12\x19\x65vent_store.client.shared\"\xb0\x01\n\x04UUID\x12@\n\nstructured\x18\x01 \x01(\x0b\x32*.event_store.client.shared.UUID.StructuredH\x00\x12\x10\n\x06string\x18\x02 \x01(\tH\x00\x1aK\n\nStructured\x12\x1d\n\x15most_significant_bits\x18\x01 \x01(\x03\x12\x1e\n\x16least_significant_bits\x18\x02 \x01(\x03\x42\x07\n\x05value\"\x07\n\x05\x45mpty\",\n\x10StreamIdentifier\x12\x12\n\nstreamName\x18\x03 \x01(\x0cJ\x04\x08\x01\x10\x03\x42&\n$com.eventstore.dbclient.proto.sharedb\x06proto3'
)




_UUID_STRUCTURED = _descriptor.Descriptor(
  name='Structured',
  full_name='event_store.client.shared.UUID.Structured',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='most_significant_bits', full_name='event_store.client.shared.UUID.Structured.most_significant_bits', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='least_significant_bits', full_name='event_store.client.shared.UUID.Structured.least_significant_bits', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=211,
)

_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='event_store.client.shared.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='structured', full_name='event_store.client.shared.UUID.structured', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string', full_name='event_store.client.shared.UUID.string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_UUID_STRUCTURED, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='event_store.client.shared.UUID.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=44,
  serialized_end=220,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='event_store.client.shared.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=229,
)


_STREAMIDENTIFIER = _descriptor.Descriptor(
  name='StreamIdentifier',
  full_name='event_store.client.shared.StreamIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='streamName', full_name='event_store.client.shared.StreamIdentifier.streamName', index=0,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=275,
)

_UUID_STRUCTURED.containing_type = _UUID
_UUID.fields_by_name['structured'].message_type = _UUID_STRUCTURED
_UUID.oneofs_by_name['value'].fields.append(
  _UUID.fields_by_name['structured'])
_UUID.fields_by_name['structured'].containing_oneof = _UUID.oneofs_by_name['value']
_UUID.oneofs_by_name['value'].fields.append(
  _UUID.fields_by_name['string'])
_UUID.fields_by_name['string'].containing_oneof = _UUID.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['StreamIdentifier'] = _STREAMIDENTIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {

  'Structured' : _reflection.GeneratedProtocolMessageType('Structured', (_message.Message,), {
    'DESCRIPTOR' : _UUID_STRUCTURED,
    '__module__' : 'shared_pb2'
    # @@protoc_insertion_point(class_scope:event_store.client.shared.UUID.Structured)
    })
  ,
  'DESCRIPTOR' : _UUID,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:event_store.client.shared.UUID)
  })
_sym_db.RegisterMessage(UUID)
_sym_db.RegisterMessage(UUID.Structured)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:event_store.client.shared.Empty)
  })
_sym_db.RegisterMessage(Empty)

StreamIdentifier = _reflection.GeneratedProtocolMessageType('StreamIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _STREAMIDENTIFIER,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:event_store.client.shared.StreamIdentifier)
  })
_sym_db.RegisterMessage(StreamIdentifier)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
